### ISSUE TITLE
Accessing helpers in models?

### ISSUE THREAD

**Issue by markdieselcore** [browner12/helpers#3]
Is there a way to access custom helpers inside models?

**Comment by browner12** [comment]
these are global functions so they should be accessible anywhere. is it not working for you? are you getting any specific error message?

**Comment by markdieselcore** [comment]
I apologize. User error.

On a side note, thanks for this great package. I may be submitting a few pull requests for some generic, but useful functions I have written while using this package in my projects. If you are taking community contributions to the package, that is.

**Comment by browner12** [comment]
sounds good. no promises, but i'll definitely take a look at them.  just so you're aware, my criteria will be how generic are they (do they work for a lot of people), and how helpful are they. 

I do realize that some of the current ones probably don't really match this exactly, but originally I had designed the package for myself and my personal projects, and they got left in. for community contributions, however, I'll probably be a little more stringent just so it doesn't turn into a free-for-all bloated package, since it's so easy to make your own.

thanks for the kind words as well, glad it's helped you!
